name: Upload to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -U pip build
          
      - name: Build
        run: |
          python -m build
          
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*

  publish:
    name: Publish
    needs: build
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist
          
      - name: Publish a Python distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        if: github.event.action != 'published'
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_TOKEN }}
